service: japdb
provider:
  name: aws
  runtime: python3.7
functions:
  booklist:
    handler: src/book.list
    events:
      - http:
          path: booklist
          method: get
  meaning:
    handler: src/meaning.get
    events:
      - http:
          path: meaning
          method: get
  uploadhandle:
    handler: src/upload.dictionaryjson
    events:
      - s3:
          bucket: dictionary-json-bucket
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json
          existing: true